# Generated by Django 4.0.4 on 2022-05-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='author_photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('lang', models.CharField(choices=[('Руский', 'Руский'), ('Английский', 'Английский'), ('Казахский', 'Казахский')], default='Руский', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последний изм.')),
                ('rating', models.IntegerField(default=5, verbose_name='rating')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Главное Категория',
                'verbose_name_plural': 'Главные Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=150)),
                ('payment_method', models.CharField(choices=[('Картой', 'Картой'), ('Наличкой', 'Наличкой')], max_length=20)),
                ('iin', models.CharField(max_length=25)),
                ('bank_iin', models.CharField(max_length=25)),
                ('cvv_iin', models.CharField(max_length=4)),
                ('transaction_id', models.IntegerField()),
                ('totalbook', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='publisher_photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Издатели',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('iin', models.CharField(max_length=25, verbose_name='ИИН')),
                ('bank_iin', models.CharField(blank=True, max_length=25, verbose_name='Банковский счёт')),
                ('cvv_iin', models.CharField(blank=True, max_length=4, verbose_name='cvv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.maincategory', verbose_name='Главное Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiDiStoreApp.publisher', verbose_name='Издатель'),
        ),
    ]
